### ISSUE TITLE
Regarding the scRNA-seq data

### ISSUE THREAD

**Issue by 1667857557** [dengchunyu/scPagwas_reproduce#3]
您好，
  论文中使用的scRNA-seq大部分都是正常组织的数据，若我想进行特定疾病的探究，使用对应疾病的scRNA-seq数据进行分析是否可行呢？这与前者相比映射的基因是否更加精准（因为我看类似的工具[scDRS]有发表过使用疾病scRNA-seq数据的文章）

**Comment by dengchunyu** [comment]
可以使用疾病的数据，在接下来的软件延伸工作中我们使用的就是疾病单细胞数据，发现肿瘤的gwas数据产生的得分能够很好的区分正常和肿瘤上皮细胞。然而，我们发现在具体的分析中，单细胞类型的选择对pcc基因结果影响很大，这需要注意，比如，同时选择免疫细胞和上皮细胞，以及只选择上皮细胞的结果在精度上会差别很大（这一步如果能熟练使用scPagwas，则不需要重新取单细胞子集计算，因为gPas得分不受单细胞数量的影响，基于此可以直接计算细胞子集的pcc基因），另外一点需要注意的是，我们软件的结果中TRS得分是基于正向的pcc基因进行计算的，然而，反向的pcc基因的结果我们发现也很有意思，只是需要更进一步的分析和解释，这两者在分析时可以都看看。

Yu-Feng Huang ***@***.***> 于2023年9月7日周四 10:14写道：

**Comment by 1667857557** [comment]
感谢您的回复，您的意思是指部位特异性疾病使用对应的部位的正常scRNA-seq数据和疾病scRNA-seq在scPagwas包中都是可行的，但疾病scRNA-seq的分群效果更加好么

**Comment by dengchunyu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    是的，基于疾病gwas最好用疾病单细胞，能够更精确的找到具体相关的细胞。
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Yu-Feng ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/7/2023 22:02
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Chunyu ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [dengchunyu/scPagwas_reproduce] Regarding the scRNA-seq data (Issue #3)
        
      
    
  
  
感谢您的回复，您的意思是指部位特异性疾病使用对应的部位的正常scRNA-seq数据和疾病scRNA-seq在scPagwas包中都是可行的，但疾病scRNA-seq的分群效果更加好么

可以使用疾病的数据，在接下来的软件延伸工作中我们使用的就是疾病单细胞数据，发现肿瘤的gwas数据产生的得分能够很好的区分正常和肿瘤上皮细胞。然而，我们发现在具体的分析中，单细胞类型的选择对pcc基因结果影响很大，这需要注意，比如，同时选择免疫细胞和上皮细胞，以及只选择上皮细胞的结果在精度上会差别很大（这一步如果能熟练使用scPagwas，则不需要重新取单细胞子集计算，因为gPas得分不受单细胞数量的影响，基于此可以直接计算细胞子集的pcc基因），另外一点需要注意的是，我们软件的结果中TRS得分是基于正向的pcc基因进行计算的，然而，反向的pcc基因的结果我们发现也很有意思，只是需要更进一步的分析和解释，这两者在分析时可以都看看。 Yu-Feng Huang @.> 于2023年9月7日周四 10:14写道：
…

**Comment by 1667857557** [comment]
了解，感谢老师解惑
